version: '3.8'

services:
  db:
    image: postgres:15
    container_name: clickbeard-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: clickbeard
      POSTGRES_PASSWORD: clickbeard123
      POSTGRES_DB: clickbeard
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - clickbeard-net

volumes:
  pgdata:

networks:
  clickbeard-net:
